services:
  db:
    image: postgres:17-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: haggle_dev
      POSTGRES_PASSWORD: haggle
    volumes:
      - haggle-pg-data:/var/lib/postgresql/data

  db-test:
    image: postgres:17-alpine
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: haggle_test
      POSTGRES_PASSWORD: haggle
    tmpfs:
      - /var/lib/postgresql/data

  meilisearch:
    image: getmeili/meilisearch:v1.13
    ports:
      - '7700:7700'
    environment:
      MEILI_MASTER_KEY: haggle-dev-key
      MEILI_ENV: development
    volumes:
      - haggle-meili-data:/meili_data

volumes:
  haggle-pg-data:
  haggle-meili-data:
